from rest_framework import serializers

from hope_control_manager.models import User


class UserListSerializer(serializers.HyperlinkedModelSerializer[User]):
    class Meta:
        model = User
        fields = ["url", "username", "email", "is_staff"]


class UserDetailSerializer(UserListSerializer):
    groups = serializers.HyperlinkedIdentityField(
        view_name="user-groups-list",  # Must match the view name generated by the router
        lookup_url_kwarg="parent_lookup_user_groups",  # Matches the lookup in the router
    )

    class Meta:
        model = User
        fields = UserListSerializer.Meta.fields + ["groups"]
